package net.minecraft.init;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockLiquid;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockSand;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;

public class Blocks
{
    public static final Block AIR = (Block)Block.field_149771_c.getById("air");
    public static final Block STONE = (Block)Block.field_149771_c.getById("stone");
    public static final BlockGrass GRASS = (BlockGrass)Block.field_149771_c.getById("grass");
    public static final Block DIRT = (Block)Block.field_149771_c.getById("dirt");
    public static final Block COBBLESTONE = (Block)Block.field_149771_c.getById("cobblestone");
    public static final Block PLANKS = (Block)Block.field_149771_c.getById("planks");
    public static final Block SAPLING = (Block)Block.field_149771_c.getById("sapling");
    public static final Block BEDROCK = (Block)Block.field_149771_c.getById("bedrock");
    public static final BlockLiquid FLOWING_WATER = (BlockLiquid)Block.field_149771_c.getById("flowing_water");
    public static final Block WATER = (Block)Block.field_149771_c.getById("water");
    public static final BlockLiquid FLOWING_LAVA = (BlockLiquid)Block.field_149771_c.getById("flowing_lava");
    public static final Block LAVA = (Block)Block.field_149771_c.getById("lava");
    public static final BlockSand SAND = (BlockSand)Block.field_149771_c.getById("sand");
    public static final Block GRAVEL = (Block)Block.field_149771_c.getById("gravel");
    public static final Block GOLD_ORE = (Block)Block.field_149771_c.getById("gold_ore");
    public static final Block IRON_ORE = (Block)Block.field_149771_c.getById("iron_ore");
    public static final Block COAL_ORE = (Block)Block.field_149771_c.getById("coal_ore");
    public static final Block LOG = (Block)Block.field_149771_c.getById("log");
    public static final Block LOG_2 = (Block)Block.field_149771_c.getById("log2");
    public static final BlockLeaves LEAVES = (BlockLeaves)Block.field_149771_c.getById("leaves");
    public static final BlockLeaves LEAVES_2 = (BlockLeaves)Block.field_149771_c.getById("leaves2");
    public static final Block SPONGE = (Block)Block.field_149771_c.getById("sponge");
    public static final Block GLASS = (Block)Block.field_149771_c.getById("glass");
    public static final Block LAPIS_ORE = (Block)Block.field_149771_c.getById("lapis_ore");
    public static final Block LAPIS_BLOCK = (Block)Block.field_149771_c.getById("lapis_block");
    public static final Block DISPENSER = (Block)Block.field_149771_c.getById("dispenser");
    public static final Block SANDSTONE = (Block)Block.field_149771_c.getById("sandstone");
    public static final Block NOTEBLOCK = (Block)Block.field_149771_c.getById("noteblock");
    public static final Block BED = (Block)Block.field_149771_c.getById("bed");
    public static final Block GOLDEN_RAIL = (Block)Block.field_149771_c.getById("golden_rail");
    public static final Block DETECTOR_RAIL = (Block)Block.field_149771_c.getById("detector_rail");
    public static final BlockPistonBase STICKY_PISTON = (BlockPistonBase)Block.field_149771_c.getById("sticky_piston");
    public static final Block WEB = (Block)Block.field_149771_c.getById("web");
    public static final BlockTallGrass TALLGRASS = (BlockTallGrass)Block.field_149771_c.getById("tallgrass");
    public static final BlockDeadBush DEADBUSH = (BlockDeadBush)Block.field_149771_c.getById("deadbush");
    public static final BlockPistonBase PISTON = (BlockPistonBase)Block.field_149771_c.getById("piston");
    public static final BlockPistonExtension PISTON_HEAD = (BlockPistonExtension)Block.field_149771_c.getById("piston_head");
    public static final Block WOOL = (Block)Block.field_149771_c.getById("wool");
    public static final BlockPistonMoving PISTON_EXTENSION = (BlockPistonMoving)Block.field_149771_c.getById("piston_extension");
    public static final BlockFlower YELLOW_FLOWER = (BlockFlower)Block.field_149771_c.getById("yellow_flower");
    public static final BlockFlower RED_FLOWER = (BlockFlower)Block.field_149771_c.getById("red_flower");
    public static final BlockBush BROWN_MUSHROOM = (BlockBush)Block.field_149771_c.getById("brown_mushroom");
    public static final BlockBush RED_MUSHROOM = (BlockBush)Block.field_149771_c.getById("red_mushroom");
    public static final Block GOLD_BLOCK = (Block)Block.field_149771_c.getById("gold_block");
    public static final Block IRON_BLOCK = (Block)Block.field_149771_c.getById("iron_block");
    public static final BlockSlab DOUBLE_STONE_SLAB = (BlockSlab)Block.field_149771_c.getById("double_stone_slab");
    public static final BlockSlab STONE_SLAB = (BlockSlab)Block.field_149771_c.getById("stone_slab");
    public static final Block BRICK_BLOCK = (Block)Block.field_149771_c.getById("brick_block");
    public static final Block TNT = (Block)Block.field_149771_c.getById("tnt");
    public static final Block BOOKSHELF = (Block)Block.field_149771_c.getById("bookshelf");
    public static final Block MOSSY_COBBLESTONE = (Block)Block.field_149771_c.getById("mossy_cobblestone");
    public static final Block OBSIDIAN = (Block)Block.field_149771_c.getById("obsidian");
    public static final Block TORCH = (Block)Block.field_149771_c.getById("torch");
    public static final BlockFire FIRE = (BlockFire)Block.field_149771_c.getById("fire");
    public static final Block MOB_SPAWNER = (Block)Block.field_149771_c.getById("mob_spawner");
    public static final Block OAK_STAIRS = (Block)Block.field_149771_c.getById("oak_stairs");
    public static final BlockChest CHEST = (BlockChest)Block.field_149771_c.getById("chest");
    public static final BlockRedstoneWire REDSTONE_WIRE = (BlockRedstoneWire)Block.field_149771_c.getById("redstone_wire");
    public static final Block DIAMOND_ORE = (Block)Block.field_149771_c.getById("diamond_ore");
    public static final Block DIAMOND_BLOCK = (Block)Block.field_149771_c.getById("diamond_block");
    public static final Block CRAFTING_TABLE = (Block)Block.field_149771_c.getById("crafting_table");
    public static final Block WHEAT = (Block)Block.field_149771_c.getById("wheat");
    public static final Block FARMLAND = (Block)Block.field_149771_c.getById("farmland");
    public static final Block FURNACE = (Block)Block.field_149771_c.getById("furnace");
    public static final Block LIT_FURNACE = (Block)Block.field_149771_c.getById("lit_furnace");
    public static final Block STANDING_SIGN = (Block)Block.field_149771_c.getById("standing_sign");
    public static final Block WOODEN_DOOR = (Block)Block.field_149771_c.getById("wooden_door");
    public static final Block LADDER = (Block)Block.field_149771_c.getById("ladder");
    public static final Block RAIL = (Block)Block.field_149771_c.getById("rail");
    public static final Block STONE_STAIRS = (Block)Block.field_149771_c.getById("stone_stairs");
    public static final Block WALL_SIGN = (Block)Block.field_149771_c.getById("wall_sign");
    public static final Block LEVER = (Block)Block.field_149771_c.getById("lever");
    public static final Block STONE_PRESSURE_PLATE = (Block)Block.field_149771_c.getById("stone_pressure_plate");
    public static final Block IRON_DOOR = (Block)Block.field_149771_c.getById("iron_door");
    public static final Block WOODEN_PRESSURE_PLATE = (Block)Block.field_149771_c.getById("wooden_pressure_plate");
    public static final Block REDSTONE_ORE = (Block)Block.field_149771_c.getById("redstone_ore");
    public static final Block LIT_REDSTONE_ORE = (Block)Block.field_149771_c.getById("lit_redstone_ore");
    public static final Block UNLIT_REDSTONE_TORCH = (Block)Block.field_149771_c.getById("unlit_redstone_torch");
    public static final Block REDSTONE_TORCH = (Block)Block.field_149771_c.getById("redstone_torch");
    public static final Block STONE_BUTTON = (Block)Block.field_149771_c.getById("stone_button");
    public static final Block SNOW_LAYER = (Block)Block.field_149771_c.getById("snow_layer");
    public static final Block ICE = (Block)Block.field_149771_c.getById("ice");
    public static final Block SNOW = (Block)Block.field_149771_c.getById("snow");
    public static final Block CACTUS = (Block)Block.field_149771_c.getById("cactus");
    public static final Block CLAY = (Block)Block.field_149771_c.getById("clay");
    public static final Block REEDS = (Block)Block.field_149771_c.getById("reeds");
    public static final Block JUKEBOX = (Block)Block.field_149771_c.getById("jukebox");
    public static final Block FENCE = (Block)Block.field_149771_c.getById("fence");
    public static final Block PUMPKIN = (Block)Block.field_149771_c.getById("pumpkin");
    public static final Block NETHERRACK = (Block)Block.field_149771_c.getById("netherrack");
    public static final Block SOUL_SAND = (Block)Block.field_149771_c.getById("soul_sand");
    public static final Block GLOWSTONE = (Block)Block.field_149771_c.getById("glowstone");
    public static final BlockPortal PORTAL = (BlockPortal)Block.field_149771_c.getById("portal");
    public static final Block LIT_PUMPKIN = (Block)Block.field_149771_c.getById("lit_pumpkin");
    public static final Block CAKE = (Block)Block.field_149771_c.getById("cake");
    public static final BlockRedstoneRepeater UNPOWERED_REPEATER = (BlockRedstoneRepeater)Block.field_149771_c.getById("unpowered_repeater");
    public static final BlockRedstoneRepeater POWERED_REPEATER = (BlockRedstoneRepeater)Block.field_149771_c.getById("powered_repeater");
    public static final Block TRAPDOOR = (Block)Block.field_149771_c.getById("trapdoor");
    public static final Block MONSTER_EGG = (Block)Block.field_149771_c.getById("monster_egg");
    public static final Block STONEBRICK = (Block)Block.field_149771_c.getById("stonebrick");
    public static final Block BROWN_MUSHROOM_BLOCK = (Block)Block.field_149771_c.getById("brown_mushroom_block");
    public static final Block RED_MUSHROOM_BLOCK = (Block)Block.field_149771_c.getById("red_mushroom_block");
    public static final Block IRON_BARS = (Block)Block.field_149771_c.getById("iron_bars");
    public static final Block GLASS_PANE = (Block)Block.field_149771_c.getById("glass_pane");
    public static final Block MELON_BLOCK = (Block)Block.field_149771_c.getById("melon_block");
    public static final Block PUMPKIN_STEM = (Block)Block.field_149771_c.getById("pumpkin_stem");
    public static final Block MELON_STEM = (Block)Block.field_149771_c.getById("melon_stem");
    public static final Block VINE = (Block)Block.field_149771_c.getById("vine");
    public static final Block FENCE_GATE = (Block)Block.field_149771_c.getById("fence_gate");
    public static final Block BRICK_STAIRS = (Block)Block.field_149771_c.getById("brick_stairs");
    public static final Block STONE_BRICK_STAIRS = (Block)Block.field_149771_c.getById("stone_brick_stairs");
    public static final BlockMycelium MYCELIUM = (BlockMycelium)Block.field_149771_c.getById("mycelium");
    public static final Block WATERLILY = (Block)Block.field_149771_c.getById("waterlily");
    public static final Block NETHER_BRICK = (Block)Block.field_149771_c.getById("nether_brick");
    public static final Block NETHER_BRICK_FENCE = (Block)Block.field_149771_c.getById("nether_brick_fence");
    public static final Block NETHER_BRICK_STAIRS = (Block)Block.field_149771_c.getById("nether_brick_stairs");
    public static final Block NETHER_WART = (Block)Block.field_149771_c.getById("nether_wart");
    public static final Block ENCHANTING_TABLE = (Block)Block.field_149771_c.getById("enchanting_table");
    public static final Block BREWING_STAND = (Block)Block.field_149771_c.getById("brewing_stand");
    public static final BlockCauldron CAULDRON = (BlockCauldron)Block.field_149771_c.getById("cauldron");
    public static final Block END_PORTAL = (Block)Block.field_149771_c.getById("end_portal");
    public static final Block END_PORTAL_FRAME = (Block)Block.field_149771_c.getById("end_portal_frame");
    public static final Block END_STONE = (Block)Block.field_149771_c.getById("end_stone");
    public static final Block DRAGON_EGG = (Block)Block.field_149771_c.getById("dragon_egg");
    public static final Block REDSTONE_LAMP = (Block)Block.field_149771_c.getById("redstone_lamp");
    public static final Block LIT_REDSTONE_LAMP = (Block)Block.field_149771_c.getById("lit_redstone_lamp");
    public static final BlockSlab DOUBLE_WOODEN_SLAB = (BlockSlab)Block.field_149771_c.getById("double_wooden_slab");
    public static final BlockSlab WOODEN_SLAB = (BlockSlab)Block.field_149771_c.getById("wooden_slab");
    public static final Block COCOA = (Block)Block.field_149771_c.getById("cocoa");
    public static final Block SANDSTONE_STAIRS = (Block)Block.field_149771_c.getById("sandstone_stairs");
    public static final Block EMERALD_ORE = (Block)Block.field_149771_c.getById("emerald_ore");
    public static final Block ENDER_CHEST = (Block)Block.field_149771_c.getById("ender_chest");
    public static final BlockTripWireHook TRIPWIRE_HOOK = (BlockTripWireHook)Block.field_149771_c.getById("tripwire_hook");
    public static final Block TRIPWIRE = (Block)Block.field_149771_c.getById("tripwire");
    public static final Block EMERALD_BLOCK = (Block)Block.field_149771_c.getById("emerald_block");
    public static final Block SPRUCE_STAIRS = (Block)Block.field_149771_c.getById("spruce_stairs");
    public static final Block BIRCH_STAIRS = (Block)Block.field_149771_c.getById("birch_stairs");
    public static final Block JUNGLE_STAIRS = (Block)Block.field_149771_c.getById("jungle_stairs");
    public static final Block COMMAND_BLOCK = (Block)Block.field_149771_c.getById("command_block");
    public static final BlockBeacon BEACON = (BlockBeacon)Block.field_149771_c.getById("beacon");
    public static final Block COBBLESTONE_WALL = (Block)Block.field_149771_c.getById("cobblestone_wall");
    public static final Block FLOWER_POT = (Block)Block.field_149771_c.getById("flower_pot");
    public static final Block CARROTS = (Block)Block.field_149771_c.getById("carrots");
    public static final Block POTATOES = (Block)Block.field_149771_c.getById("potatoes");
    public static final Block WOODEN_BUTTON = (Block)Block.field_149771_c.getById("wooden_button");
    public static final Block SKULL = (Block)Block.field_149771_c.getById("skull");
    public static final Block ANVIL = (Block)Block.field_149771_c.getById("anvil");
    public static final Block TRAPPED_CHEST = (Block)Block.field_149771_c.getById("trapped_chest");
    public static final Block LIGHT_WEIGHTED_PRESSURE_PLATE = (Block)Block.field_149771_c.getById("light_weighted_pressure_plate");
    public static final Block HEAVY_WEIGHTED_PRESSURE_PLATE = (Block)Block.field_149771_c.getById("heavy_weighted_pressure_plate");
    public static final BlockRedstoneComparator UNPOWERED_COMPARATOR = (BlockRedstoneComparator)Block.field_149771_c.getById("unpowered_comparator");
    public static final BlockRedstoneComparator POWERED_COMPARATOR = (BlockRedstoneComparator)Block.field_149771_c.getById("powered_comparator");
    public static final BlockDaylightDetector DAYLIGHT_DETECTOR = (BlockDaylightDetector)Block.field_149771_c.getById("daylight_detector");
    public static final Block REDSTONE_BLOCK = (Block)Block.field_149771_c.getById("redstone_block");
    public static final Block QUARTZ_ORE = (Block)Block.field_149771_c.getById("quartz_ore");
    public static final BlockHopper HOPPER = (BlockHopper)Block.field_149771_c.getById("hopper");
    public static final Block QUARTZ_BLOCK = (Block)Block.field_149771_c.getById("quartz_block");
    public static final Block QUARTZ_STAIRS = (Block)Block.field_149771_c.getById("quartz_stairs");
    public static final Block ACTIVATOR_RAIL = (Block)Block.field_149771_c.getById("activator_rail");
    public static final Block DROPPER = (Block)Block.field_149771_c.getById("dropper");
    public static final Block STAINED_HARDENED_CLAY = (Block)Block.field_149771_c.getById("stained_hardened_clay");
    public static final Block HAY_BLOCK = (Block)Block.field_149771_c.getById("hay_block");
    public static final Block CARPET = (Block)Block.field_149771_c.getById("carpet");
    public static final Block HARDENED_CLAY = (Block)Block.field_149771_c.getById("hardened_clay");
    public static final Block COAL_BLOCK = (Block)Block.field_149771_c.getById("coal_block");
    public static final Block PACKED_ICE = (Block)Block.field_149771_c.getById("packed_ice");
    public static final Block ACACIA_STAIRS = (Block)Block.field_149771_c.getById("acacia_stairs");
    public static final Block DARK_OAK_STAIRS = (Block)Block.field_149771_c.getById("dark_oak_stairs");
    public static final BlockDoublePlant DOUBLE_PLANT = (BlockDoublePlant)Block.field_149771_c.getById("double_plant");
    public static final BlockStainedGlass STAINED_GLASS = (BlockStainedGlass)Block.field_149771_c.getById("stained_glass");
    public static final BlockStainedGlassPane STAINED_GLASS_PANE = (BlockStainedGlassPane)Block.field_149771_c.getById("stained_glass_pane");
    private static final String __OBFID = "CL_00000204";
}